---
- name: Install required packages
  apt: name={{ item }} state=latest
  with_items: "{{ common_apt_packages }}"
  tags:
    - packages

- name: install docker python dependencies
  pip: name={{ item }}
  with_items: "{{ common_pip_packages }}"
  tags:
    - packages